// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZe19OcG-PIe1j5KfM7lTGpCFDI_sgHDc',
    appId: '1:412220027812:web:2b7df6b1c9c0b9782d8731',
    messagingSenderId: '412220027812',
    projectId: 'dataloot-archive',
    authDomain: 'dataloot-archive.firebaseapp.com',
    storageBucket: 'dataloot-archive.firebasestorage.app',
    measurementId: 'G-EE9CL8XYJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZeRQ6N1q1KkIlSfNaZzyYsVRXHfdtJOM',
    appId: '1:412220027812:android:1e9df40fb70165892d8731',
    messagingSenderId: '412220027812',
    projectId: 'dataloot-archive',
    storageBucket: 'dataloot-archive.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtUhUemEijoHPMan3nTXB6w4zfbdmXWjw',
    appId: '1:412220027812:ios:48e9459b86c4516b2d8731',
    messagingSenderId: '412220027812',
    projectId: 'dataloot-archive',
    storageBucket: 'dataloot-archive.firebasestorage.app',
    iosBundleId: 'com.example.datalootArchive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtUhUemEijoHPMan3nTXB6w4zfbdmXWjw',
    appId: '1:412220027812:ios:48e9459b86c4516b2d8731',
    messagingSenderId: '412220027812',
    projectId: 'dataloot-archive',
    storageBucket: 'dataloot-archive.firebasestorage.app',
    iosBundleId: 'com.example.datalootArchive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZe19OcG-PIe1j5KfM7lTGpCFDI_sgHDc',
    appId: '1:412220027812:web:eeea8fc2f48f0a882d8731',
    messagingSenderId: '412220027812',
    projectId: 'dataloot-archive',
    authDomain: 'dataloot-archive.firebaseapp.com',
    storageBucket: 'dataloot-archive.firebasestorage.app',
    measurementId: 'G-R5PWHE6GPY',
  );
}
